name: client
description: 'A new Flutter project.'
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  dio: ^5.5.0+1
  toastification: ^2.1.0
  flutter_native_splash: ^2.4.1
  flutter_bloc: ^8.1.6
  shared_preferences: ^2.3.1
  flutter_calendar_carousel: ^2.4.3
  loading_animation_widget: ^1.2.1
  image_picker: ^1.1.2
  flutter_launcher_icons: ^0.13.1
  intl: ^0.18.1
  intrinsic_dimension: ^0.3.1
  google_sign_in: ^6.2.1
  url_launcher: ^6.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/icons/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/font/Poppins-Regular.ttf
        - asset: assets/font/Poppins-Light.ttf
          weight: 300
        - asset: assets/font/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/font/Poppins-Bold.ttf
          weight: 700
